// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScenarioOuter.proto

package com.wcy.scenario;

public interface ChunkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wcy.scenario.Chunk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes chunk = 1;</code>
   */
  com.google.protobuf.ByteString getChunk();
}
