// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScenarioOuter.proto

package com.wcy.scenario;

public interface CompanyNameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wcy.scenario.CompanyName)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string companyName = 1;</code>
   */
  String getCompanyName();
  /**
   * <code>string companyName = 1;</code>
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();
}
