// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScenarioOuter.proto

package com.wcy.scenario;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wcy.scenario.Empty)
    com.google.protobuf.MessageOrBuilder {
}
