// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScenarioOuter.proto

package com.wcy.scenario;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wcy.scenario.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
