// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScenarioOuter.proto

package com.wcy.scenario;

public final class ScenarioOuter {
  private ScenarioOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wcy_scenario_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wcy_scenario_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wcy_scenario_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wcy_scenario_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wcy_scenario_Chunk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wcy_scenario_Chunk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wcy_scenario_CompanyName_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wcy_scenario_CompanyName_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wcy_scenario_Company_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wcy_scenario_Company_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wcy_scenario_Sentence_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wcy_scenario_Sentence_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023ScenarioOuter.proto\022\020com.wcy.scenario\"" +
      "\026\n\006Person\022\014\n\004name\030\001 \001(\t\"\007\n\005Empty\"\026\n\005Chun" +
      "k\022\r\n\005chunk\030\001 \001(\014\"\"\n\013CompanyName\022\023\n\013compa" +
      "nyName\030\001 \001(\t\")\n\007Company\022\014\n\004name\030\001 \001(\t\022\020\n" +
      "\010storedIn\030\002 \001(\t\"\034\n\010Sentence\022\020\n\010sentence\030" +
      "\001 \001(\t2\365\002\n\010Scenario\022@\n\007CheekIn\022\030.com.wcy." +
      "scenario.Person\032\027.com.wcy.scenario.Empty" +
      "\"\000(\001\022?\n\007Chunker\022\027.com.wcy.scenario.Empty" +
      "\032\027.com.wcy.scenario.Chunk\"\0000\001\022L\n\014GetComp" +
      "anies\022\035.com.wcy.scenario.CompanyName\032\031.c" +
      "om.wcy.scenario.Company\"\0000\001\022M\n\023BatchWrit" +
      "eCompanies\022\031.com.wcy.scenario.Company\032\027." +
      "com.wcy.scenario.Empty\"\000(\001\022I\n\tTranslate\022" +
      "\032.com.wcy.scenario.Sentence\032\032.com.wcy.sc" +
      "enario.Sentence\"\000(\0010\001B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_wcy_scenario_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_wcy_scenario_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wcy_scenario_Person_descriptor,
        new String[] { "Name", });
    internal_static_com_wcy_scenario_Empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_wcy_scenario_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wcy_scenario_Empty_descriptor,
        new String[] { });
    internal_static_com_wcy_scenario_Chunk_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_wcy_scenario_Chunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wcy_scenario_Chunk_descriptor,
        new String[] { "Chunk", });
    internal_static_com_wcy_scenario_CompanyName_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_wcy_scenario_CompanyName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wcy_scenario_CompanyName_descriptor,
        new String[] { "CompanyName", });
    internal_static_com_wcy_scenario_Company_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_wcy_scenario_Company_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wcy_scenario_Company_descriptor,
        new String[] { "Name", "StoredIn", });
    internal_static_com_wcy_scenario_Sentence_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_wcy_scenario_Sentence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wcy_scenario_Sentence_descriptor,
        new String[] { "Sentence", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
