// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScenarioOuter.proto

package com.wcy.scenario;

public interface SentenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.wcy.scenario.Sentence)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sentence = 1;</code>
   */
  String getSentence();
  /**
   * <code>string sentence = 1;</code>
   */
  com.google.protobuf.ByteString
      getSentenceBytes();
}
